export const rolePermissions = {
    SUPER_ADMIN: [
        "DASHBOARD",
        "ORDERS",
        "VENDORS",
        "SUB_ADMINS",
        "CATEGORIES",
        "SUBCATEGORIES",
        "BRANDS",
        "PRODUCTS",
        "RIDERS",
        "CUSTOMERS",
        "SUSPENDED_CUSTOMERS",
        "TERMINATED_CUSTOMERS",
        "TICKETS",
        "REFUNDS",
        "SETTINGS",
        "BANNERS",
        "COUPONS",
        "DELIVERY_CHARGES",
        "REPORTS",
        "PAYOUTS",
        "INVOICES",
        "RIDER_TERMINATIONS"
    ],

    VENDOR_OWNER: [
        "DASHBOARD",
        "VENDOR_ORDERS",
        "VENDOR_PRODUCTS",
        "REPORTS",
        "STAFF",
        "VENDOR_SUPPORT",
        "PAYOUTS",
        "INVOICES",
        "CUSTOMERS",
        "ANNOUNCEMENTS",
        "ABOUT_US",
        "TERMS_AND_CONDITIONS",
        "PRIVACY_POLICY",
        "PLATFORM_LINKS",
    ]
};
